version: '3.8'
services:
  dev-db:
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - google-oauth
networks:
  google-oauth:
